/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Data.gltf --transform 
Files: Data.gltf [218.72KB] > C:\Users\chris\Documents\3D Models\Portfolio\Data\Data-transformed.glb [70.6KB] (68%)
Author: Alex Martire (https://sketchfab.com/alexmartire)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/data-center-low-poly-59b31b45e80c484e98e1839ab1acc90b
Title: Data Center (low-poly)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Data(props) {
  const { nodes, materials } = useGLTF('/Data-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cluster_MetalCase_0.geometry} material={materials.PaletteMaterial001} position={[-0.004, 5.901, -16]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cluster_Frente_0.geometry} material={materials.Frente} position={[-0.004, 5.901, -16]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cluster_Verde_0.geometry} material={materials.PaletteMaterial002} position={[-0.004, 5.901, -16]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cluster_Amarelo_0.geometry} material={materials.PaletteMaterial003} position={[-0.004, 5.901, -16]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LampTeto003_LampTeto_0.geometry} material={materials.PaletteMaterial004} position={[0.019, 17.9, -17]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Data-transformed.glb')
