/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Develop.gltf --transform 
Files: Develop.gltf [502.7KB] > C:\Users\chris\Documents\3D Models\Portfolio\Develop\Develop-transformed.glb [252.54KB] (50%)
Author: Helindu (https://sketchfab.com/Helindu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-clipart-webdev-f3d8f1a7174847d994ab698e265f9672
Title: 3D Clipart - WebDev
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Develop(props) {
  const { nodes, materials } = useGLTF('/Develop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.JS_text001_0.geometry} material={materials.PaletteMaterial001} position={[3.767, -0.071, 0.509]} />
    </group>
  )
}

useGLTF.preload('/Develop-transformed.glb')
