/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Shoe.gltf --transform 
Files: Shoe.gltf [5.34MB] > C:\Users\chris\Documents\3D Models\Portfolio\Shoe\Shoe-transformed.glb [926.94KB] (83%)
Author: SofiaWolfie (https://sketchfab.com/SofiaWolfie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-tc-7900-sail-fb2de7469d4f43c1aba7f878ef935cce
Title: Nike TC 7900 Sail
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shoe(props) {
  const { nodes, materials } = useGLTF('/Shoe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.metall_svart} position={[0.067, 0.044, -0.048]} rotation={[-3.008, -0.005, -2.218]} scale={[-0.01, 0.01, 0.01]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.006']} scale={[0.11, 0.108, 0.108]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} scale={0.108} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Material} scale={0.108} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.material_grund} scale={0.108} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.sko_sula_underdel} scale={0.108} />
    </group>
  )
}

useGLTF.preload('/Shoe-transformed.glb')
